services:
  - type: web
    name: platlog
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn platlog.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: platlog.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
